name: Build and Deploy CloudPulse

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 742573506475.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t cloudpulse-devops-app:latest ./

      - name: Tag Docker Image
        run: |
          docker tag cloudpulse-devops-app:latest 742573506475.dkr.ecr.eu-north-1.amazonaws.com/cloudpulse-devops-app:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 742573506475.dkr.ecr.eu-north-1.amazonaws.com/cloudpulse-devops-app:latest

      - name: Deploy on EC2 Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 60s
          script: |
            echo "Connected to EC2 successfully"

            sudo systemctl start docker || true

            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 742573506475.dkr.ecr.eu-north-1.amazonaws.com

            docker pull 742573506475.dkr.ecr.eu-north-1.amazonaws.com/cloudpulse-devops-app:latest

            docker rm -f cloudpulse-devops-app || true

            docker run -d --name cloudpulse-devops-app -e PORT=3000 -p 30081:3000 742573506475.dkr.ecr.eu-north-1.amazonaws.com/cloudpulse-devops-app:latest

            docker ps

            echo "Deployment completed successfully"
